name: Test

on: [pull_request, push]

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
